# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext  
        FOS\UserBundle\Model\UserInterface: bcrypt
        
    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }     
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: /admin/.*
            form_login:
                check_path: /admin/login_check
                login_path: /admin/signin
                username_parameter: _username
                password_parameter: _password
                csrf_parameter: _csrf_token
                intention: authenticate               
                post_only: true
                use_referer: false
                default_target_path: /admin/dashboard
                always_use_default_target_path: true
                provider: chain_provider
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:
              path:   /admin/signout
              target: /admin/signin
              invalidate_session: false
              delete_cookies:
                  a: { path: null, domain: null }
                  b: { path: null, domain: null }
            anonymous: ~ 
    
    access_control:
        public_login_page:
            path: /admin/signin
            roles: [IS_AUTHENTICATED_ANONYMOUSLY]
        public_request_page:
            path: /admin/request
            roles: [IS_AUTHENTICATED_ANONYMOUSLY]
        public_request_page:
            path: /admin/send-email
            roles: [IS_AUTHENTICATED_ANONYMOUSLY]
        public_request_page:
            path: /admin/check-email
            roles: [IS_AUTHENTICATED_ANONYMOUSLY]
        public_request_page:
            path: /admin/reset/.*
            roles: [IS_AUTHENTICATED_ANONYMOUSLY]
        public_request_page:
            path: /admin/request
            roles: [IS_AUTHENTICATED_ANONYMOUSLY]
        public_logout_page:
            path: /admin/signout
            roles: [IS_AUTHENTICATED_ANONYMOUSLY]
        admin_secured_pages:
            path: /admin/.*
            roles: [ROLE_ADMIN] 
